# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 2.0.29
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ip4g
from ip4g.models.ike_policy_options import IKEPolicyOptions  # noqa: E501
from ip4g.rest import ApiException


class TestIKEPolicyOptions(unittest.TestCase):
    """IKEPolicyOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIKEPolicyOptions(self):
        """Test IKEPolicyOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ip4g.models.ike_policy_options.IKEPolicyOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
