# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 2.0.29
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ip4g
from ip4g.models.console_language import ConsoleLanguage  # noqa: E501
from ip4g.rest import ApiException


class TestConsoleLanguage(unittest.TestCase):
    """ConsoleLanguage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsoleLanguage(self):
        """Test ConsoleLanguage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ip4g.models.console_language.ConsoleLanguage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
