# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ip4g
from ip4g.models.volumes_clone_cancel import VolumesCloneCancel  # noqa: E501
from ip4g.rest import ApiException


class TestVolumesCloneCancel(unittest.TestCase):
    """VolumesCloneCancel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVolumesCloneCancel(self):
        """Test VolumesCloneCancel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ip4g.models.volumes_clone_cancel.VolumesCloneCancel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
