# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 2.0.52
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ip4g
from ip4g.api.default_api import DefaultApi  # noqa: E501
from ip4g.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = ip4g.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pcloud_cloudinstances_storagetypes_get(self):
        """Test case for pcloud_cloudinstances_storagetypes_get

        Get the list of storage types available for the given cloud instance's associated plan.   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
