# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.pvm_instance_update_response import PVMInstanceUpdateResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestPVMInstanceUpdateResponse(unittest.TestCase):
    """PVMInstanceUpdateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPVMInstanceUpdateResponse(self):
        """Test PVMInstanceUpdateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.pvm_instance_update_response.PVMInstanceUpdateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
