# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ip4g
from ip4g.api.p_cloud_jobs_api import PCloudJobsApi  # noqa: E501
from ip4g.rest import ApiException


class TestPCloudJobsApi(unittest.TestCase):
    """PCloudJobsApi unit test stubs"""

    def setUp(self):
        self.api = ip4g.api.p_cloud_jobs_api.PCloudJobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pcloud_cloudinstances_jobs_delete(self):
        """Test case for pcloud_cloudinstances_jobs_delete

        Delete a cloud instance job  # noqa: E501
        """
        pass

    def test_pcloud_cloudinstances_jobs_get(self):
        """Test case for pcloud_cloudinstances_jobs_get

        List the detail of a job  # noqa: E501
        """
        pass

    def test_pcloud_cloudinstances_jobs_getall(self):
        """Test case for pcloud_cloudinstances_jobs_getall

        List up to the last 5 jobs initiated by the cloud instance  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
