# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 2.0.29
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ip4g
from ip4g.models.ip_sec_policy_create import IPSecPolicyCreate  # noqa: E501
from ip4g.rest import ApiException


class TestIPSecPolicyCreate(unittest.TestCase):
    """IPSecPolicyCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIPSecPolicyCreate(self):
        """Test IPSecPolicyCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ip4g.models.ip_sec_policy_create.IPSecPolicyCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
