# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.pvm_instance_create import PVMInstanceCreate  # noqa: E501
from swagger_client.rest import ApiException


class TestPVMInstanceCreate(unittest.TestCase):
    """PVMInstanceCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPVMInstanceCreate(self):
        """Test PVMInstanceCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.pvm_instance_create.PVMInstanceCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
