# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.p_cloud_system_pools_api import PCloudSystemPoolsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPCloudSystemPoolsApi(unittest.TestCase):
    """PCloudSystemPoolsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.p_cloud_system_pools_api.PCloudSystemPoolsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pcloud_systempools_get(self):
        """Test case for pcloud_systempools_get

        List of available system pools within a particular DataCenter  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
