# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ip4g.configuration import Configuration


class ConsoleLanguages(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'console_languages': 'list[ConsoleLanguage]'
    }

    attribute_map = {
        'console_languages': 'consoleLanguages'
    }

    def __init__(self, console_languages=None, _configuration=None):  # noqa: E501
        """ConsoleLanguages - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._console_languages = None
        self.discriminator = None

        self.console_languages = console_languages

    @property
    def console_languages(self):
        """Gets the console_languages of this ConsoleLanguages.  # noqa: E501

        console languages  # noqa: E501

        :return: The console_languages of this ConsoleLanguages.  # noqa: E501
        :rtype: list[ConsoleLanguage]
        """
        return self._console_languages

    @console_languages.setter
    def console_languages(self, console_languages):
        """Sets the console_languages of this ConsoleLanguages.

        console languages  # noqa: E501

        :param console_languages: The console_languages of this ConsoleLanguages.  # noqa: E501
        :type: list[ConsoleLanguage]
        """
        if self._configuration.client_side_validation and console_languages is None:
            raise ValueError("Invalid value for `console_languages`, must not be `None`")  # noqa: E501

        self._console_languages = console_languages

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConsoleLanguages, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConsoleLanguages):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ConsoleLanguages):
            return True

        return self.to_dict() != other.to_dict()
