# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 2.0.29
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ip4g.configuration import Configuration


class IKEPolicy(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'authentication': 'IKEPolicyAuthentication',
        'dh_group': 'int',
        'encryption': 'str',
        'id': 'str',
        'key_lifetime': 'KeyLifetime',
        'name': 'str',
        'version': 'int'
    }

    attribute_map = {
        'authentication': 'authentication',
        'dh_group': 'dhGroup',
        'encryption': 'encryption',
        'id': 'id',
        'key_lifetime': 'keyLifetime',
        'name': 'name',
        'version': 'version'
    }

    def __init__(self, authentication=None, dh_group=None, encryption=None, id=None, key_lifetime=None, name=None, version=None, _configuration=None):  # noqa: E501
        """IKEPolicy - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._authentication = None
        self._dh_group = None
        self._encryption = None
        self._id = None
        self._key_lifetime = None
        self._name = None
        self._version = None
        self.discriminator = None

        self.authentication = authentication
        self.dh_group = dh_group
        self.encryption = encryption
        self.id = id
        self.key_lifetime = key_lifetime
        self.name = name
        self.version = version

    @property
    def authentication(self):
        """Gets the authentication of this IKEPolicy.  # noqa: E501


        :return: The authentication of this IKEPolicy.  # noqa: E501
        :rtype: IKEPolicyAuthentication
        """
        return self._authentication

    @authentication.setter
    def authentication(self, authentication):
        """Sets the authentication of this IKEPolicy.


        :param authentication: The authentication of this IKEPolicy.  # noqa: E501
        :type: IKEPolicyAuthentication
        """
        if self._configuration.client_side_validation and authentication is None:
            raise ValueError("Invalid value for `authentication`, must not be `None`")  # noqa: E501

        self._authentication = authentication

    @property
    def dh_group(self):
        """Gets the dh_group of this IKEPolicy.  # noqa: E501

        DH group of the IKE Policy  # noqa: E501

        :return: The dh_group of this IKEPolicy.  # noqa: E501
        :rtype: int
        """
        return self._dh_group

    @dh_group.setter
    def dh_group(self, dh_group):
        """Sets the dh_group of this IKEPolicy.

        DH group of the IKE Policy  # noqa: E501

        :param dh_group: The dh_group of this IKEPolicy.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and dh_group is None:
            raise ValueError("Invalid value for `dh_group`, must not be `None`")  # noqa: E501

        self._dh_group = dh_group

    @property
    def encryption(self):
        """Gets the encryption of this IKEPolicy.  # noqa: E501

        encryption of the IKE Policy  # noqa: E501

        :return: The encryption of this IKEPolicy.  # noqa: E501
        :rtype: str
        """
        return self._encryption

    @encryption.setter
    def encryption(self, encryption):
        """Sets the encryption of this IKEPolicy.

        encryption of the IKE Policy  # noqa: E501

        :param encryption: The encryption of this IKEPolicy.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and encryption is None:
            raise ValueError("Invalid value for `encryption`, must not be `None`")  # noqa: E501
        allowed_values = ["3des-cbc", "aes-128-cbc", "aes-128-gcm", "aes-192-cbc", "aes-256-cbc", "aes-256-gcm", "des-cbc"]  # noqa: E501
        if (self._configuration.client_side_validation and
                encryption not in allowed_values):
            raise ValueError(
                "Invalid value for `encryption` ({0}), must be one of {1}"  # noqa: E501
                .format(encryption, allowed_values)
            )

        self._encryption = encryption

    @property
    def id(self):
        """Gets the id of this IKEPolicy.  # noqa: E501

        unique identifier of the IKE Policy object  # noqa: E501

        :return: The id of this IKEPolicy.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this IKEPolicy.

        unique identifier of the IKE Policy object  # noqa: E501

        :param id: The id of this IKEPolicy.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def key_lifetime(self):
        """Gets the key_lifetime of this IKEPolicy.  # noqa: E501


        :return: The key_lifetime of this IKEPolicy.  # noqa: E501
        :rtype: KeyLifetime
        """
        return self._key_lifetime

    @key_lifetime.setter
    def key_lifetime(self, key_lifetime):
        """Sets the key_lifetime of this IKEPolicy.


        :param key_lifetime: The key_lifetime of this IKEPolicy.  # noqa: E501
        :type: KeyLifetime
        """
        if self._configuration.client_side_validation and key_lifetime is None:
            raise ValueError("Invalid value for `key_lifetime`, must not be `None`")  # noqa: E501

        self._key_lifetime = key_lifetime

    @property
    def name(self):
        """Gets the name of this IKEPolicy.  # noqa: E501

        name of the IKE Policy  # noqa: E501

        :return: The name of this IKEPolicy.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this IKEPolicy.

        name of the IKE Policy  # noqa: E501

        :param name: The name of this IKEPolicy.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def version(self):
        """Gets the version of this IKEPolicy.  # noqa: E501

        version of the IKE Policy  # noqa: E501

        :return: The version of this IKEPolicy.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this IKEPolicy.

        version of the IKE Policy  # noqa: E501

        :param version: The version of this IKEPolicy.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IKEPolicy, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IKEPolicy):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IKEPolicy):
            return True

        return self.to_dict() != other.to_dict()
