# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 2.0.29
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ip4g.configuration import Configuration


class IKEPolicyOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'authentications': 'IKEPolicyAuthentications',
        'dh_groups': 'IKEPolicyDhGroups',
        'encryptions': 'IKEPolicyEncryptions',
        'versions': 'PolicyVersions'
    }

    attribute_map = {
        'authentications': 'authentications',
        'dh_groups': 'dhGroups',
        'encryptions': 'encryptions',
        'versions': 'versions'
    }

    def __init__(self, authentications=None, dh_groups=None, encryptions=None, versions=None, _configuration=None):  # noqa: E501
        """IKEPolicyOptions - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._authentications = None
        self._dh_groups = None
        self._encryptions = None
        self._versions = None
        self.discriminator = None

        self.authentications = authentications
        self.dh_groups = dh_groups
        self.encryptions = encryptions
        self.versions = versions

    @property
    def authentications(self):
        """Gets the authentications of this IKEPolicyOptions.  # noqa: E501


        :return: The authentications of this IKEPolicyOptions.  # noqa: E501
        :rtype: IKEPolicyAuthentications
        """
        return self._authentications

    @authentications.setter
    def authentications(self, authentications):
        """Sets the authentications of this IKEPolicyOptions.


        :param authentications: The authentications of this IKEPolicyOptions.  # noqa: E501
        :type: IKEPolicyAuthentications
        """
        if self._configuration.client_side_validation and authentications is None:
            raise ValueError("Invalid value for `authentications`, must not be `None`")  # noqa: E501

        self._authentications = authentications

    @property
    def dh_groups(self):
        """Gets the dh_groups of this IKEPolicyOptions.  # noqa: E501


        :return: The dh_groups of this IKEPolicyOptions.  # noqa: E501
        :rtype: IKEPolicyDhGroups
        """
        return self._dh_groups

    @dh_groups.setter
    def dh_groups(self, dh_groups):
        """Sets the dh_groups of this IKEPolicyOptions.


        :param dh_groups: The dh_groups of this IKEPolicyOptions.  # noqa: E501
        :type: IKEPolicyDhGroups
        """
        if self._configuration.client_side_validation and dh_groups is None:
            raise ValueError("Invalid value for `dh_groups`, must not be `None`")  # noqa: E501

        self._dh_groups = dh_groups

    @property
    def encryptions(self):
        """Gets the encryptions of this IKEPolicyOptions.  # noqa: E501


        :return: The encryptions of this IKEPolicyOptions.  # noqa: E501
        :rtype: IKEPolicyEncryptions
        """
        return self._encryptions

    @encryptions.setter
    def encryptions(self, encryptions):
        """Sets the encryptions of this IKEPolicyOptions.


        :param encryptions: The encryptions of this IKEPolicyOptions.  # noqa: E501
        :type: IKEPolicyEncryptions
        """
        if self._configuration.client_side_validation and encryptions is None:
            raise ValueError("Invalid value for `encryptions`, must not be `None`")  # noqa: E501

        self._encryptions = encryptions

    @property
    def versions(self):
        """Gets the versions of this IKEPolicyOptions.  # noqa: E501


        :return: The versions of this IKEPolicyOptions.  # noqa: E501
        :rtype: PolicyVersions
        """
        return self._versions

    @versions.setter
    def versions(self, versions):
        """Sets the versions of this IKEPolicyOptions.


        :param versions: The versions of this IKEPolicyOptions.  # noqa: E501
        :type: PolicyVersions
        """
        if self._configuration.client_side_validation and versions is None:
            raise ValueError("Invalid value for `versions`, must not be `None`")  # noqa: E501

        self._versions = versions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IKEPolicyOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IKEPolicyOptions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IKEPolicyOptions):
            return True

        return self.to_dict() != other.to_dict()
