# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 2.0.29
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ip4g.configuration import Configuration


class Options(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'vpnaas_options': 'VPNaaSOptions'
    }

    attribute_map = {
        'vpnaas_options': 'vpnaasOptions'
    }

    def __init__(self, vpnaas_options=None, _configuration=None):  # noqa: E501
        """Options - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._vpnaas_options = None
        self.discriminator = None

        self.vpnaas_options = vpnaas_options

    @property
    def vpnaas_options(self):
        """Gets the vpnaas_options of this Options.  # noqa: E501


        :return: The vpnaas_options of this Options.  # noqa: E501
        :rtype: VPNaaSOptions
        """
        return self._vpnaas_options

    @vpnaas_options.setter
    def vpnaas_options(self, vpnaas_options):
        """Sets the vpnaas_options of this Options.


        :param vpnaas_options: The vpnaas_options of this Options.  # noqa: E501
        :type: VPNaaSOptions
        """
        if self._configuration.client_side_validation and vpnaas_options is None:
            raise ValueError("Invalid value for `vpnaas_options`, must not be `None`")  # noqa: E501

        self._vpnaas_options = vpnaas_options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Options, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Options):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Options):
            return True

        return self.to_dict() != other.to_dict()
