# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 2.0.56
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ip4g.configuration import Configuration


class PrivateConnectionCreate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bandwidth': 'Bandwidth',
        'name': 'PrivateConnectionName',
        'project_id': 'str',
        'service_producer_project_id': 'str',
        'vpc_network_name': 'str'
    }

    attribute_map = {
        'bandwidth': 'bandwidth',
        'name': 'name',
        'project_id': 'project_id',
        'service_producer_project_id': 'service_producer_project_id',
        'vpc_network_name': 'vpc_network_name'
    }

    def __init__(self, bandwidth=None, name=None, project_id=None, service_producer_project_id=None, vpc_network_name=None, _configuration=None):  # noqa: E501
        """PrivateConnectionCreate - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._bandwidth = None
        self._name = None
        self._project_id = None
        self._service_producer_project_id = None
        self._vpc_network_name = None
        self.discriminator = None

        self.bandwidth = bandwidth
        if name is not None:
            self.name = name
        self.project_id = project_id
        self.service_producer_project_id = service_producer_project_id
        self.vpc_network_name = vpc_network_name

    @property
    def bandwidth(self):
        """Gets the bandwidth of this PrivateConnectionCreate.  # noqa: E501


        :return: The bandwidth of this PrivateConnectionCreate.  # noqa: E501
        :rtype: Bandwidth
        """
        return self._bandwidth

    @bandwidth.setter
    def bandwidth(self, bandwidth):
        """Sets the bandwidth of this PrivateConnectionCreate.


        :param bandwidth: The bandwidth of this PrivateConnectionCreate.  # noqa: E501
        :type: Bandwidth
        """
        if self._configuration.client_side_validation and bandwidth is None:
            raise ValueError("Invalid value for `bandwidth`, must not be `None`")  # noqa: E501

        self._bandwidth = bandwidth

    @property
    def name(self):
        """Gets the name of this PrivateConnectionCreate.  # noqa: E501


        :return: The name of this PrivateConnectionCreate.  # noqa: E501
        :rtype: PrivateConnectionName
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PrivateConnectionCreate.


        :param name: The name of this PrivateConnectionCreate.  # noqa: E501
        :type: PrivateConnectionName
        """

        self._name = name

    @property
    def project_id(self):
        """Gets the project_id of this PrivateConnectionCreate.  # noqa: E501

        The Google Cloud Project ID of the customer.  # noqa: E501

        :return: The project_id of this PrivateConnectionCreate.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this PrivateConnectionCreate.

        The Google Cloud Project ID of the customer.  # noqa: E501

        :param project_id: The project_id of this PrivateConnectionCreate.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and project_id is None:
            raise ValueError("Invalid value for `project_id`, must not be `None`")  # noqa: E501

        self._project_id = project_id

    @property
    def service_producer_project_id(self):
        """Gets the service_producer_project_id of this PrivateConnectionCreate.  # noqa: E501

        The Google Cloud Service Producer Project ID that is peered with the customer's VPC network.  # noqa: E501

        :return: The service_producer_project_id of this PrivateConnectionCreate.  # noqa: E501
        :rtype: str
        """
        return self._service_producer_project_id

    @service_producer_project_id.setter
    def service_producer_project_id(self, service_producer_project_id):
        """Sets the service_producer_project_id of this PrivateConnectionCreate.

        The Google Cloud Service Producer Project ID that is peered with the customer's VPC network.  # noqa: E501

        :param service_producer_project_id: The service_producer_project_id of this PrivateConnectionCreate.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and service_producer_project_id is None:
            raise ValueError("Invalid value for `service_producer_project_id`, must not be `None`")  # noqa: E501

        self._service_producer_project_id = service_producer_project_id

    @property
    def vpc_network_name(self):
        """Gets the vpc_network_name of this PrivateConnectionCreate.  # noqa: E501

        The customer's Google Cloud VPC Network name that is peered with IP4G.  # noqa: E501

        :return: The vpc_network_name of this PrivateConnectionCreate.  # noqa: E501
        :rtype: str
        """
        return self._vpc_network_name

    @vpc_network_name.setter
    def vpc_network_name(self, vpc_network_name):
        """Sets the vpc_network_name of this PrivateConnectionCreate.

        The customer's Google Cloud VPC Network name that is peered with IP4G.  # noqa: E501

        :param vpc_network_name: The vpc_network_name of this PrivateConnectionCreate.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and vpc_network_name is None:
            raise ValueError("Invalid value for `vpc_network_name`, must not be `None`")  # noqa: E501

        self._vpc_network_name = vpc_network_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PrivateConnectionCreate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PrivateConnectionCreate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PrivateConnectionCreate):
            return True

        return self.to_dict() != other.to_dict()
