# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 2.0.29
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ip4g.configuration import Configuration


class Spp(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'allocated_cores': 'float',
        'available_cores': 'float',
        'host_group': 'str',
        'host_id': 'int',
        'id': 'str',
        'name': 'str',
        'pvm_instances': 'list[SppServer]',
        'reserved_cores': 'int',
        'shared_processor_pool_placement_groups': 'list[SppPlacementGroup]',
        'status': 'str',
        'status_detail': 'str'
    }

    attribute_map = {
        'allocated_cores': 'allocatedCores',
        'available_cores': 'availableCores',
        'host_group': 'hostGroup',
        'host_id': 'hostID',
        'id': 'id',
        'name': 'name',
        'pvm_instances': 'pvmInstances',
        'reserved_cores': 'reservedCores',
        'shared_processor_pool_placement_groups': 'sharedProcessorPoolPlacementGroups',
        'status': 'status',
        'status_detail': 'statusDetail'
    }

    def __init__(self, allocated_cores=None, available_cores=None, host_group=None, host_id=None, id=None, name=None, pvm_instances=None, reserved_cores=None, shared_processor_pool_placement_groups=None, status=None, status_detail=None, _configuration=None):  # noqa: E501
        """Spp - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._allocated_cores = None
        self._available_cores = None
        self._host_group = None
        self._host_id = None
        self._id = None
        self._name = None
        self._pvm_instances = None
        self._reserved_cores = None
        self._shared_processor_pool_placement_groups = None
        self._status = None
        self._status_detail = None
        self.discriminator = None

        self.allocated_cores = allocated_cores
        self.available_cores = available_cores
        if host_group is not None:
            self.host_group = host_group
        if host_id is not None:
            self.host_id = host_id
        self.id = id
        self.name = name
        if pvm_instances is not None:
            self.pvm_instances = pvm_instances
        self.reserved_cores = reserved_cores
        if shared_processor_pool_placement_groups is not None:
            self.shared_processor_pool_placement_groups = shared_processor_pool_placement_groups
        if status is not None:
            self.status = status
        if status_detail is not None:
            self.status_detail = status_detail

    @property
    def allocated_cores(self):
        """Gets the allocated_cores of this Spp.  # noqa: E501

        The amount of allocated processor cores for the Shared Processor Pool   # noqa: E501

        :return: The allocated_cores of this Spp.  # noqa: E501
        :rtype: float
        """
        return self._allocated_cores

    @allocated_cores.setter
    def allocated_cores(self, allocated_cores):
        """Sets the allocated_cores of this Spp.

        The amount of allocated processor cores for the Shared Processor Pool   # noqa: E501

        :param allocated_cores: The allocated_cores of this Spp.  # noqa: E501
        :type: float
        """
        if self._configuration.client_side_validation and allocated_cores is None:
            raise ValueError("Invalid value for `allocated_cores`, must not be `None`")  # noqa: E501

        self._allocated_cores = allocated_cores

    @property
    def available_cores(self):
        """Gets the available_cores of this Spp.  # noqa: E501

        The amount of available processor cores for the Shared Processor Pool   # noqa: E501

        :return: The available_cores of this Spp.  # noqa: E501
        :rtype: float
        """
        return self._available_cores

    @available_cores.setter
    def available_cores(self, available_cores):
        """Sets the available_cores of this Spp.

        The amount of available processor cores for the Shared Processor Pool   # noqa: E501

        :param available_cores: The available_cores of this Spp.  # noqa: E501
        :type: float
        """
        if self._configuration.client_side_validation and available_cores is None:
            raise ValueError("Invalid value for `available_cores`, must not be `None`")  # noqa: E501

        self._available_cores = available_cores

    @property
    def host_group(self):
        """Gets the host_group of this Spp.  # noqa: E501

        The host group the host belongs to  # noqa: E501

        :return: The host_group of this Spp.  # noqa: E501
        :rtype: str
        """
        return self._host_group

    @host_group.setter
    def host_group(self, host_group):
        """Sets the host_group of this Spp.

        The host group the host belongs to  # noqa: E501

        :param host_group: The host_group of this Spp.  # noqa: E501
        :type: str
        """

        self._host_group = host_group

    @property
    def host_id(self):
        """Gets the host_id of this Spp.  # noqa: E501

        The ID of the host where the Shared Processor Pool resides  # noqa: E501

        :return: The host_id of this Spp.  # noqa: E501
        :rtype: int
        """
        return self._host_id

    @host_id.setter
    def host_id(self, host_id):
        """Sets the host_id of this Spp.

        The ID of the host where the Shared Processor Pool resides  # noqa: E501

        :param host_id: The host_id of this Spp.  # noqa: E501
        :type: int
        """

        self._host_id = host_id

    @property
    def id(self):
        """Gets the id of this Spp.  # noqa: E501

        The id of the Shared Processor Pool  # noqa: E501

        :return: The id of this Spp.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Spp.

        The id of the Shared Processor Pool  # noqa: E501

        :param id: The id of this Spp.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this Spp.  # noqa: E501

        The name of the Shared Processor Pool  # noqa: E501

        :return: The name of this Spp.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Spp.

        The name of the Shared Processor Pool  # noqa: E501

        :param name: The name of this Spp.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def pvm_instances(self):
        """Gets the pvm_instances of this Spp.  # noqa: E501

        list of Power Virtual Machines (PVM) instances that are in the SPP.   # noqa: E501

        :return: The pvm_instances of this Spp.  # noqa: E501
        :rtype: list[SppServer]
        """
        return self._pvm_instances

    @pvm_instances.setter
    def pvm_instances(self, pvm_instances):
        """Sets the pvm_instances of this Spp.

        list of Power Virtual Machines (PVM) instances that are in the SPP.   # noqa: E501

        :param pvm_instances: The pvm_instances of this Spp.  # noqa: E501
        :type: list[SppServer]
        """

        self._pvm_instances = pvm_instances

    @property
    def reserved_cores(self):
        """Gets the reserved_cores of this Spp.  # noqa: E501

        The amount of reserved processor cores for the Shared Processor Pool   # noqa: E501

        :return: The reserved_cores of this Spp.  # noqa: E501
        :rtype: int
        """
        return self._reserved_cores

    @reserved_cores.setter
    def reserved_cores(self, reserved_cores):
        """Sets the reserved_cores of this Spp.

        The amount of reserved processor cores for the Shared Processor Pool   # noqa: E501

        :param reserved_cores: The reserved_cores of this Spp.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and reserved_cores is None:
            raise ValueError("Invalid value for `reserved_cores`, must not be `None`")  # noqa: E501

        self._reserved_cores = reserved_cores

    @property
    def shared_processor_pool_placement_groups(self):
        """Gets the shared_processor_pool_placement_groups of this Spp.  # noqa: E501

        list of Shared Processor Pool Placement Groups  # noqa: E501

        :return: The shared_processor_pool_placement_groups of this Spp.  # noqa: E501
        :rtype: list[SppPlacementGroup]
        """
        return self._shared_processor_pool_placement_groups

    @shared_processor_pool_placement_groups.setter
    def shared_processor_pool_placement_groups(self, shared_processor_pool_placement_groups):
        """Sets the shared_processor_pool_placement_groups of this Spp.

        list of Shared Processor Pool Placement Groups  # noqa: E501

        :param shared_processor_pool_placement_groups: The shared_processor_pool_placement_groups of this Spp.  # noqa: E501
        :type: list[SppPlacementGroup]
        """

        self._shared_processor_pool_placement_groups = shared_processor_pool_placement_groups

    @property
    def status(self):
        """Gets the status of this Spp.  # noqa: E501

        The status of the Shared Processor Pool  # noqa: E501

        :return: The status of this Spp.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Spp.

        The status of the Shared Processor Pool  # noqa: E501

        :param status: The status of this Spp.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def status_detail(self):
        """Gets the status_detail of this Spp.  # noqa: E501

        The status details of the Shared Processor Pool  # noqa: E501

        :return: The status_detail of this Spp.  # noqa: E501
        :rtype: str
        """
        return self._status_detail

    @status_detail.setter
    def status_detail(self, status_detail):
        """Sets the status_detail of this Spp.

        The status details of the Shared Processor Pool  # noqa: E501

        :param status_detail: The status_detail of this Spp.  # noqa: E501
        :type: str
        """

        self._status_detail = status_detail

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Spp, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Spp):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Spp):
            return True

        return self.to_dict() != other.to_dict()
