# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 2.0.29
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ip4g.configuration import Configuration


class SSHKey(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'creation_date': 'datetime',
        'name': 'str',
        'ssh_key': 'str'
    }

    attribute_map = {
        'creation_date': 'creationDate',
        'name': 'name',
        'ssh_key': 'sshKey'
    }

    def __init__(self, creation_date=None, name=None, ssh_key=None, _configuration=None):  # noqa: E501
        """SSHKey - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._creation_date = None
        self._name = None
        self._ssh_key = None
        self.discriminator = None

        if creation_date is not None:
            self.creation_date = creation_date
        self.name = name
        self.ssh_key = ssh_key

    @property
    def creation_date(self):
        """Gets the creation_date of this SSHKey.  # noqa: E501

        Date of sshkey creation  # noqa: E501

        :return: The creation_date of this SSHKey.  # noqa: E501
        :rtype: datetime
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date):
        """Sets the creation_date of this SSHKey.

        Date of sshkey creation  # noqa: E501

        :param creation_date: The creation_date of this SSHKey.  # noqa: E501
        :type: datetime
        """

        self._creation_date = creation_date

    @property
    def name(self):
        """Gets the name of this SSHKey.  # noqa: E501

        User defined name for the SSH key  # noqa: E501

        :return: The name of this SSHKey.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SSHKey.

        User defined name for the SSH key  # noqa: E501

        :param name: The name of this SSHKey.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def ssh_key(self):
        """Gets the ssh_key of this SSHKey.  # noqa: E501

        SSH RSA key  # noqa: E501

        :return: The ssh_key of this SSHKey.  # noqa: E501
        :rtype: str
        """
        return self._ssh_key

    @ssh_key.setter
    def ssh_key(self, ssh_key):
        """Sets the ssh_key of this SSHKey.

        SSH RSA key  # noqa: E501

        :param ssh_key: The ssh_key of this SSHKey.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and ssh_key is None:
            raise ValueError("Invalid value for `ssh_key`, must not be `None`")  # noqa: E501

        self._ssh_key = ssh_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SSHKey, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SSHKey):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SSHKey):
            return True

        return self.to_dict() != other.to_dict()
