# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 2.0.56
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ip4g.configuration import Configuration


class StorageMigrationJob(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cluster': 'bool',
        'created_at': 'datetime',
        'current_step': 'str',
        'is_paused': 'bool',
        'last_successful_step': 'str',
        'migration_id': 'str',
        'name': 'str',
        'notes': 'str',
        'started_at': 'datetime',
        'status': 'str',
        'volume_count': 'int'
    }

    attribute_map = {
        'cluster': 'Cluster',
        'created_at': 'CreatedAt',
        'current_step': 'CurrentStep',
        'is_paused': 'IsPaused',
        'last_successful_step': 'LastSuccessfulStep',
        'migration_id': 'MigrationId',
        'name': 'Name',
        'notes': 'Notes',
        'started_at': 'StartedAt',
        'status': 'Status',
        'volume_count': 'VolumeCount'
    }

    def __init__(self, cluster=None, created_at=None, current_step=None, is_paused=None, last_successful_step=None, migration_id=None, name=None, notes=None, started_at=None, status=None, volume_count=None, _configuration=None):  # noqa: E501
        """StorageMigrationJob - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._cluster = None
        self._created_at = None
        self._current_step = None
        self._is_paused = None
        self._last_successful_step = None
        self._migration_id = None
        self._name = None
        self._notes = None
        self._started_at = None
        self._status = None
        self._volume_count = None
        self.discriminator = None

        if cluster is not None:
            self.cluster = cluster
        if created_at is not None:
            self.created_at = created_at
        if current_step is not None:
            self.current_step = current_step
        if is_paused is not None:
            self.is_paused = is_paused
        if last_successful_step is not None:
            self.last_successful_step = last_successful_step
        if migration_id is not None:
            self.migration_id = migration_id
        if name is not None:
            self.name = name
        if notes is not None:
            self.notes = notes
        if started_at is not None:
            self.started_at = started_at
        if status is not None:
            self.status = status
        if volume_count is not None:
            self.volume_count = volume_count

    @property
    def cluster(self):
        """Gets the cluster of this StorageMigrationJob.  # noqa: E501

        Whether this job is cluster-aware.  # noqa: E501

        :return: The cluster of this StorageMigrationJob.  # noqa: E501
        :rtype: bool
        """
        return self._cluster

    @cluster.setter
    def cluster(self, cluster):
        """Sets the cluster of this StorageMigrationJob.

        Whether this job is cluster-aware.  # noqa: E501

        :param cluster: The cluster of this StorageMigrationJob.  # noqa: E501
        :type: bool
        """

        self._cluster = cluster

    @property
    def created_at(self):
        """Gets the created_at of this StorageMigrationJob.  # noqa: E501


        :return: The created_at of this StorageMigrationJob.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this StorageMigrationJob.


        :param created_at: The created_at of this StorageMigrationJob.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def current_step(self):
        """Gets the current_step of this StorageMigrationJob.  # noqa: E501


        :return: The current_step of this StorageMigrationJob.  # noqa: E501
        :rtype: str
        """
        return self._current_step

    @current_step.setter
    def current_step(self, current_step):
        """Sets the current_step of this StorageMigrationJob.


        :param current_step: The current_step of this StorageMigrationJob.  # noqa: E501
        :type: str
        """

        self._current_step = current_step

    @property
    def is_paused(self):
        """Gets the is_paused of this StorageMigrationJob.  # noqa: E501


        :return: The is_paused of this StorageMigrationJob.  # noqa: E501
        :rtype: bool
        """
        return self._is_paused

    @is_paused.setter
    def is_paused(self, is_paused):
        """Sets the is_paused of this StorageMigrationJob.


        :param is_paused: The is_paused of this StorageMigrationJob.  # noqa: E501
        :type: bool
        """

        self._is_paused = is_paused

    @property
    def last_successful_step(self):
        """Gets the last_successful_step of this StorageMigrationJob.  # noqa: E501


        :return: The last_successful_step of this StorageMigrationJob.  # noqa: E501
        :rtype: str
        """
        return self._last_successful_step

    @last_successful_step.setter
    def last_successful_step(self, last_successful_step):
        """Sets the last_successful_step of this StorageMigrationJob.


        :param last_successful_step: The last_successful_step of this StorageMigrationJob.  # noqa: E501
        :type: str
        """

        self._last_successful_step = last_successful_step

    @property
    def migration_id(self):
        """Gets the migration_id of this StorageMigrationJob.  # noqa: E501


        :return: The migration_id of this StorageMigrationJob.  # noqa: E501
        :rtype: str
        """
        return self._migration_id

    @migration_id.setter
    def migration_id(self, migration_id):
        """Sets the migration_id of this StorageMigrationJob.


        :param migration_id: The migration_id of this StorageMigrationJob.  # noqa: E501
        :type: str
        """

        self._migration_id = migration_id

    @property
    def name(self):
        """Gets the name of this StorageMigrationJob.  # noqa: E501


        :return: The name of this StorageMigrationJob.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this StorageMigrationJob.


        :param name: The name of this StorageMigrationJob.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def notes(self):
        """Gets the notes of this StorageMigrationJob.  # noqa: E501


        :return: The notes of this StorageMigrationJob.  # noqa: E501
        :rtype: str
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """Sets the notes of this StorageMigrationJob.


        :param notes: The notes of this StorageMigrationJob.  # noqa: E501
        :type: str
        """

        self._notes = notes

    @property
    def started_at(self):
        """Gets the started_at of this StorageMigrationJob.  # noqa: E501


        :return: The started_at of this StorageMigrationJob.  # noqa: E501
        :rtype: datetime
        """
        return self._started_at

    @started_at.setter
    def started_at(self, started_at):
        """Sets the started_at of this StorageMigrationJob.


        :param started_at: The started_at of this StorageMigrationJob.  # noqa: E501
        :type: datetime
        """

        self._started_at = started_at

    @property
    def status(self):
        """Gets the status of this StorageMigrationJob.  # noqa: E501


        :return: The status of this StorageMigrationJob.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this StorageMigrationJob.


        :param status: The status of this StorageMigrationJob.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def volume_count(self):
        """Gets the volume_count of this StorageMigrationJob.  # noqa: E501


        :return: The volume_count of this StorageMigrationJob.  # noqa: E501
        :rtype: int
        """
        return self._volume_count

    @volume_count.setter
    def volume_count(self, volume_count):
        """Sets the volume_count of this StorageMigrationJob.


        :param volume_count: The volume_count of this StorageMigrationJob.  # noqa: E501
        :type: int
        """

        self._volume_count = volume_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StorageMigrationJob, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StorageMigrationJob):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StorageMigrationJob):
            return True

        return self.to_dict() != other.to_dict()
