# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 2.0.29
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ip4g.configuration import Configuration


class StorageMigrationActionResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'migration_id': 'str',
        'status': 'str'
    }

    attribute_map = {
        'description': 'description',
        'migration_id': 'migration_id',
        'status': 'status'
    }

    def __init__(self, description=None, migration_id=None, status=None, _configuration=None):  # noqa: E501
        """StorageMigrationActionResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._description = None
        self._migration_id = None
        self._status = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if migration_id is not None:
            self.migration_id = migration_id
        if status is not None:
            self.status = status

    @property
    def description(self):
        """Gets the description of this StorageMigrationActionResponse.  # noqa: E501


        :return: The description of this StorageMigrationActionResponse.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this StorageMigrationActionResponse.


        :param description: The description of this StorageMigrationActionResponse.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def migration_id(self):
        """Gets the migration_id of this StorageMigrationActionResponse.  # noqa: E501


        :return: The migration_id of this StorageMigrationActionResponse.  # noqa: E501
        :rtype: str
        """
        return self._migration_id

    @migration_id.setter
    def migration_id(self, migration_id):
        """Sets the migration_id of this StorageMigrationActionResponse.


        :param migration_id: The migration_id of this StorageMigrationActionResponse.  # noqa: E501
        :type: str
        """

        self._migration_id = migration_id

    @property
    def status(self):
        """Gets the status of this StorageMigrationActionResponse.  # noqa: E501


        :return: The status of this StorageMigrationActionResponse.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this StorageMigrationActionResponse.


        :param status: The status of this StorageMigrationActionResponse.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StorageMigrationActionResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StorageMigrationActionResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StorageMigrationActionResponse):
            return True

        return self.to_dict() != other.to_dict()
