# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 2.0.29
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ip4g.configuration import Configuration


class VolumeGroupUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'add_volumes': 'list[str]',
        'description': 'str',
        'remove_volumes': 'list[str]',
        'volume_group_name': 'str'
    }

    attribute_map = {
        'add_volumes': 'addVolumes',
        'description': 'description',
        'remove_volumes': 'removeVolumes',
        'volume_group_name': 'volumeGroupName'
    }

    def __init__(self, add_volumes=None, description=None, remove_volumes=None, volume_group_name=None, _configuration=None):  # noqa: E501
        """VolumeGroupUpdate - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._add_volumes = None
        self._description = None
        self._remove_volumes = None
        self._volume_group_name = None
        self.discriminator = None

        if add_volumes is not None:
            self.add_volumes = add_volumes
        if description is not None:
            self.description = description
        if remove_volumes is not None:
            self.remove_volumes = remove_volumes
        self.volume_group_name = volume_group_name

    @property
    def add_volumes(self):
        """Gets the add_volumes of this VolumeGroupUpdate.  # noqa: E501


        :return: The add_volumes of this VolumeGroupUpdate.  # noqa: E501
        :rtype: list[str]
        """
        return self._add_volumes

    @add_volumes.setter
    def add_volumes(self, add_volumes):
        """Sets the add_volumes of this VolumeGroupUpdate.


        :param add_volumes: The add_volumes of this VolumeGroupUpdate.  # noqa: E501
        :type: list[str]
        """

        self._add_volumes = add_volumes

    @property
    def description(self):
        """Gets the description of this VolumeGroupUpdate.  # noqa: E501


        :return: The description of this VolumeGroupUpdate.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this VolumeGroupUpdate.


        :param description: The description of this VolumeGroupUpdate.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def remove_volumes(self):
        """Gets the remove_volumes of this VolumeGroupUpdate.  # noqa: E501


        :return: The remove_volumes of this VolumeGroupUpdate.  # noqa: E501
        :rtype: list[str]
        """
        return self._remove_volumes

    @remove_volumes.setter
    def remove_volumes(self, remove_volumes):
        """Sets the remove_volumes of this VolumeGroupUpdate.


        :param remove_volumes: The remove_volumes of this VolumeGroupUpdate.  # noqa: E501
        :type: list[str]
        """

        self._remove_volumes = remove_volumes

    @property
    def volume_group_name(self):
        """Gets the volume_group_name of this VolumeGroupUpdate.  # noqa: E501


        :return: The volume_group_name of this VolumeGroupUpdate.  # noqa: E501
        :rtype: str
        """
        return self._volume_group_name

    @volume_group_name.setter
    def volume_group_name(self, volume_group_name):
        """Sets the volume_group_name of this VolumeGroupUpdate.


        :param volume_group_name: The volume_group_name of this VolumeGroupUpdate.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and volume_group_name is None:
            raise ValueError("Invalid value for `volume_group_name`, must not be `None`")  # noqa: E501

        self._volume_group_name = volume_group_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VolumeGroupUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VolumeGroupUpdate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VolumeGroupUpdate):
            return True

        return self.to_dict() != other.to_dict()
