# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 2.0.29
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ip4g.configuration import Configuration


class VolumeTransferCreateTransfer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'no_snapshots': 'bool',
        'volume_id': 'str'
    }

    attribute_map = {
        'name': 'name',
        'no_snapshots': 'noSnapshots',
        'volume_id': 'volumeID'
    }

    def __init__(self, name=None, no_snapshots=False, volume_id=None, _configuration=None):  # noqa: E501
        """VolumeTransferCreateTransfer - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._no_snapshots = None
        self._volume_id = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if no_snapshots is not None:
            self.no_snapshots = no_snapshots
        self.volume_id = volume_id

    @property
    def name(self):
        """Gets the name of this VolumeTransferCreateTransfer.  # noqa: E501

        The name of the object  # noqa: E501

        :return: The name of this VolumeTransferCreateTransfer.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VolumeTransferCreateTransfer.

        The name of the object  # noqa: E501

        :param name: The name of this VolumeTransferCreateTransfer.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def no_snapshots(self):
        """Gets the no_snapshots of this VolumeTransferCreateTransfer.  # noqa: E501

        Transfer volume without snapshots  # noqa: E501

        :return: The no_snapshots of this VolumeTransferCreateTransfer.  # noqa: E501
        :rtype: bool
        """
        return self._no_snapshots

    @no_snapshots.setter
    def no_snapshots(self, no_snapshots):
        """Sets the no_snapshots of this VolumeTransferCreateTransfer.

        Transfer volume without snapshots  # noqa: E501

        :param no_snapshots: The no_snapshots of this VolumeTransferCreateTransfer.  # noqa: E501
        :type: bool
        """

        self._no_snapshots = no_snapshots

    @property
    def volume_id(self):
        """Gets the volume_id of this VolumeTransferCreateTransfer.  # noqa: E501

        The UUID of the volume  # noqa: E501

        :return: The volume_id of this VolumeTransferCreateTransfer.  # noqa: E501
        :rtype: str
        """
        return self._volume_id

    @volume_id.setter
    def volume_id(self, volume_id):
        """Sets the volume_id of this VolumeTransferCreateTransfer.

        The UUID of the volume  # noqa: E501

        :param volume_id: The volume_id of this VolumeTransferCreateTransfer.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and volume_id is None:
            raise ValueError("Invalid value for `volume_id`, must not be `None`")  # noqa: E501

        self._volume_id = volume_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VolumeTransferCreateTransfer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VolumeTransferCreateTransfer):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VolumeTransferCreateTransfer):
            return True

        return self.to_dict() != other.to_dict()
