# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 2.0.29
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ip4g.configuration import Configuration


class VPNConnectionUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ike_policy': 'str',
        'ip_sec_policy': 'str',
        'name': 'str',
        'peer_gateway_address': 'PeerGatewayAddress'
    }

    attribute_map = {
        'ike_policy': 'ikePolicy',
        'ip_sec_policy': 'ipSecPolicy',
        'name': 'name',
        'peer_gateway_address': 'peerGatewayAddress'
    }

    def __init__(self, ike_policy=None, ip_sec_policy=None, name=None, peer_gateway_address=None, _configuration=None):  # noqa: E501
        """VPNConnectionUpdate - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._ike_policy = None
        self._ip_sec_policy = None
        self._name = None
        self._peer_gateway_address = None
        self.discriminator = None

        if ike_policy is not None:
            self.ike_policy = ike_policy
        if ip_sec_policy is not None:
            self.ip_sec_policy = ip_sec_policy
        if name is not None:
            self.name = name
        if peer_gateway_address is not None:
            self.peer_gateway_address = peer_gateway_address

    @property
    def ike_policy(self):
        """Gets the ike_policy of this VPNConnectionUpdate.  # noqa: E501

        unique identifier of IKEPolicy selected for this VPNConnection  # noqa: E501

        :return: The ike_policy of this VPNConnectionUpdate.  # noqa: E501
        :rtype: str
        """
        return self._ike_policy

    @ike_policy.setter
    def ike_policy(self, ike_policy):
        """Sets the ike_policy of this VPNConnectionUpdate.

        unique identifier of IKEPolicy selected for this VPNConnection  # noqa: E501

        :param ike_policy: The ike_policy of this VPNConnectionUpdate.  # noqa: E501
        :type: str
        """

        self._ike_policy = ike_policy

    @property
    def ip_sec_policy(self):
        """Gets the ip_sec_policy of this VPNConnectionUpdate.  # noqa: E501

        unique identifier of IPSecPolicy selected for this VPNConnection  # noqa: E501

        :return: The ip_sec_policy of this VPNConnectionUpdate.  # noqa: E501
        :rtype: str
        """
        return self._ip_sec_policy

    @ip_sec_policy.setter
    def ip_sec_policy(self, ip_sec_policy):
        """Sets the ip_sec_policy of this VPNConnectionUpdate.

        unique identifier of IPSecPolicy selected for this VPNConnection  # noqa: E501

        :param ip_sec_policy: The ip_sec_policy of this VPNConnectionUpdate.  # noqa: E501
        :type: str
        """

        self._ip_sec_policy = ip_sec_policy

    @property
    def name(self):
        """Gets the name of this VPNConnectionUpdate.  # noqa: E501

        VPN Connection name  # noqa: E501

        :return: The name of this VPNConnectionUpdate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VPNConnectionUpdate.

        VPN Connection name  # noqa: E501

        :param name: The name of this VPNConnectionUpdate.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def peer_gateway_address(self):
        """Gets the peer_gateway_address of this VPNConnectionUpdate.  # noqa: E501


        :return: The peer_gateway_address of this VPNConnectionUpdate.  # noqa: E501
        :rtype: PeerGatewayAddress
        """
        return self._peer_gateway_address

    @peer_gateway_address.setter
    def peer_gateway_address(self, peer_gateway_address):
        """Sets the peer_gateway_address of this VPNConnectionUpdate.


        :param peer_gateway_address: The peer_gateway_address of this VPNConnectionUpdate.  # noqa: E501
        :type: PeerGatewayAddress
        """

        self._peer_gateway_address = peer_gateway_address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VPNConnectionUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VPNConnectionUpdate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VPNConnectionUpdate):
            return True

        return self.to_dict() != other.to_dict()
