# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class MaximumStorageAllocation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'storage_type': 'str',
        'max_allocation_size': 'int',
        'storage_pool': 'str'
    }

    attribute_map = {
        'storage_type': 'storageType',
        'max_allocation_size': 'maxAllocationSize',
        'storage_pool': 'storagePool'
    }

    def __init__(self, storage_type=None, max_allocation_size=None, storage_pool=None, _configuration=None):  # noqa: E501
        """MaximumStorageAllocation - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._storage_type = None
        self._max_allocation_size = None
        self._storage_pool = None
        self.discriminator = None

        self.storage_type = storage_type
        self.max_allocation_size = max_allocation_size
        self.storage_pool = storage_pool

    @property
    def storage_type(self):
        """Gets the storage_type of this MaximumStorageAllocation.  # noqa: E501

        Storage type  # noqa: E501

        :return: The storage_type of this MaximumStorageAllocation.  # noqa: E501
        :rtype: str
        """
        return self._storage_type

    @storage_type.setter
    def storage_type(self, storage_type):
        """Sets the storage_type of this MaximumStorageAllocation.

        Storage type  # noqa: E501

        :param storage_type: The storage_type of this MaximumStorageAllocation.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and storage_type is None:
            raise ValueError("Invalid value for `storage_type`, must not be `None`")  # noqa: E501

        self._storage_type = storage_type

    @property
    def max_allocation_size(self):
        """Gets the max_allocation_size of this MaximumStorageAllocation.  # noqa: E501

        Maximum allocation storage size (GB)  # noqa: E501

        :return: The max_allocation_size of this MaximumStorageAllocation.  # noqa: E501
        :rtype: int
        """
        return self._max_allocation_size

    @max_allocation_size.setter
    def max_allocation_size(self, max_allocation_size):
        """Sets the max_allocation_size of this MaximumStorageAllocation.

        Maximum allocation storage size (GB)  # noqa: E501

        :param max_allocation_size: The max_allocation_size of this MaximumStorageAllocation.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and max_allocation_size is None:
            raise ValueError("Invalid value for `max_allocation_size`, must not be `None`")  # noqa: E501

        self._max_allocation_size = max_allocation_size

    @property
    def storage_pool(self):
        """Gets the storage_pool of this MaximumStorageAllocation.  # noqa: E501

        Storage pool  # noqa: E501

        :return: The storage_pool of this MaximumStorageAllocation.  # noqa: E501
        :rtype: str
        """
        return self._storage_pool

    @storage_pool.setter
    def storage_pool(self, storage_pool):
        """Sets the storage_pool of this MaximumStorageAllocation.

        Storage pool  # noqa: E501

        :param storage_pool: The storage_pool of this MaximumStorageAllocation.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and storage_pool is None:
            raise ValueError("Invalid value for `storage_pool`, must not be `None`")  # noqa: E501

        self._storage_pool = storage_pool

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MaximumStorageAllocation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MaximumStorageAllocation):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MaximumStorageAllocation):
            return True

        return self.to_dict() != other.to_dict()
