# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Network(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ip_address_metrics': 'NetworkIpAddressMetrics',
        'ip_address_ranges': 'list[IPAddressRange]',
        'jumbo': 'bool',
        'cidr': 'str',
        'gateway': 'str',
        'name': 'str',
        'network_id': 'str',
        'public_ip_address_ranges': 'list[IPAddressRange]',
        'type': 'str',
        'vlan_id': 'float',
        'dns_servers': 'list[str]'
    }

    attribute_map = {
        'ip_address_metrics': 'ipAddressMetrics',
        'ip_address_ranges': 'ipAddressRanges',
        'jumbo': 'jumbo',
        'cidr': 'cidr',
        'gateway': 'gateway',
        'name': 'name',
        'network_id': 'networkID',
        'public_ip_address_ranges': 'publicIPAddressRanges',
        'type': 'type',
        'vlan_id': 'vlanID',
        'dns_servers': 'dnsServers'
    }

    def __init__(self, ip_address_metrics=None, ip_address_ranges=None, jumbo=None, cidr=None, gateway=None, name=None, network_id=None, public_ip_address_ranges=None, type='vlan', vlan_id=None, dns_servers=None, _configuration=None):  # noqa: E501
        """Network - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._ip_address_metrics = None
        self._ip_address_ranges = None
        self._jumbo = None
        self._cidr = None
        self._gateway = None
        self._name = None
        self._network_id = None
        self._public_ip_address_ranges = None
        self._type = None
        self._vlan_id = None
        self._dns_servers = None
        self.discriminator = None

        self.ip_address_metrics = ip_address_metrics
        self.ip_address_ranges = ip_address_ranges
        self.jumbo = jumbo
        self.cidr = cidr
        if gateway is not None:
            self.gateway = gateway
        self.name = name
        self.network_id = network_id
        if public_ip_address_ranges is not None:
            self.public_ip_address_ranges = public_ip_address_ranges
        self.type = type
        self.vlan_id = vlan_id
        self.dns_servers = dns_servers

    @property
    def ip_address_metrics(self):
        """Gets the ip_address_metrics of this Network.  # noqa: E501


        :return: The ip_address_metrics of this Network.  # noqa: E501
        :rtype: NetworkIpAddressMetrics
        """
        return self._ip_address_metrics

    @ip_address_metrics.setter
    def ip_address_metrics(self, ip_address_metrics):
        """Sets the ip_address_metrics of this Network.


        :param ip_address_metrics: The ip_address_metrics of this Network.  # noqa: E501
        :type: NetworkIpAddressMetrics
        """
        if self._configuration.client_side_validation and ip_address_metrics is None:
            raise ValueError("Invalid value for `ip_address_metrics`, must not be `None`")  # noqa: E501

        self._ip_address_metrics = ip_address_metrics

    @property
    def ip_address_ranges(self):
        """Gets the ip_address_ranges of this Network.  # noqa: E501

        IP Address Ranges  # noqa: E501

        :return: The ip_address_ranges of this Network.  # noqa: E501
        :rtype: list[IPAddressRange]
        """
        return self._ip_address_ranges

    @ip_address_ranges.setter
    def ip_address_ranges(self, ip_address_ranges):
        """Sets the ip_address_ranges of this Network.

        IP Address Ranges  # noqa: E501

        :param ip_address_ranges: The ip_address_ranges of this Network.  # noqa: E501
        :type: list[IPAddressRange]
        """
        if self._configuration.client_side_validation and ip_address_ranges is None:
            raise ValueError("Invalid value for `ip_address_ranges`, must not be `None`")  # noqa: E501

        self._ip_address_ranges = ip_address_ranges

    @property
    def jumbo(self):
        """Gets the jumbo of this Network.  # noqa: E501

        MTU Jumbo Network enabled  # noqa: E501

        :return: The jumbo of this Network.  # noqa: E501
        :rtype: bool
        """
        return self._jumbo

    @jumbo.setter
    def jumbo(self, jumbo):
        """Sets the jumbo of this Network.

        MTU Jumbo Network enabled  # noqa: E501

        :param jumbo: The jumbo of this Network.  # noqa: E501
        :type: bool
        """
        if self._configuration.client_side_validation and jumbo is None:
            raise ValueError("Invalid value for `jumbo`, must not be `None`")  # noqa: E501

        self._jumbo = jumbo

    @property
    def cidr(self):
        """Gets the cidr of this Network.  # noqa: E501

        Network in CIDR notation (192.168.0.0/24)  # noqa: E501

        :return: The cidr of this Network.  # noqa: E501
        :rtype: str
        """
        return self._cidr

    @cidr.setter
    def cidr(self, cidr):
        """Sets the cidr of this Network.

        Network in CIDR notation (192.168.0.0/24)  # noqa: E501

        :param cidr: The cidr of this Network.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and cidr is None:
            raise ValueError("Invalid value for `cidr`, must not be `None`")  # noqa: E501

        self._cidr = cidr

    @property
    def gateway(self):
        """Gets the gateway of this Network.  # noqa: E501

        Gateway IP Address  # noqa: E501

        :return: The gateway of this Network.  # noqa: E501
        :rtype: str
        """
        return self._gateway

    @gateway.setter
    def gateway(self, gateway):
        """Sets the gateway of this Network.

        Gateway IP Address  # noqa: E501

        :param gateway: The gateway of this Network.  # noqa: E501
        :type: str
        """

        self._gateway = gateway

    @property
    def name(self):
        """Gets the name of this Network.  # noqa: E501

        Network Name  # noqa: E501

        :return: The name of this Network.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Network.

        Network Name  # noqa: E501

        :param name: The name of this Network.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def network_id(self):
        """Gets the network_id of this Network.  # noqa: E501

        Unique Network ID  # noqa: E501

        :return: The network_id of this Network.  # noqa: E501
        :rtype: str
        """
        return self._network_id

    @network_id.setter
    def network_id(self, network_id):
        """Sets the network_id of this Network.

        Unique Network ID  # noqa: E501

        :param network_id: The network_id of this Network.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and network_id is None:
            raise ValueError("Invalid value for `network_id`, must not be `None`")  # noqa: E501

        self._network_id = network_id

    @property
    def public_ip_address_ranges(self):
        """Gets the public_ip_address_ranges of this Network.  # noqa: E501

        Public IP Address Ranges (for pub-vlan networks)  # noqa: E501

        :return: The public_ip_address_ranges of this Network.  # noqa: E501
        :rtype: list[IPAddressRange]
        """
        return self._public_ip_address_ranges

    @public_ip_address_ranges.setter
    def public_ip_address_ranges(self, public_ip_address_ranges):
        """Sets the public_ip_address_ranges of this Network.

        Public IP Address Ranges (for pub-vlan networks)  # noqa: E501

        :param public_ip_address_ranges: The public_ip_address_ranges of this Network.  # noqa: E501
        :type: list[IPAddressRange]
        """

        self._public_ip_address_ranges = public_ip_address_ranges

    @property
    def type(self):
        """Gets the type of this Network.  # noqa: E501

        Type of Network {vlan, pub-vlan}  # noqa: E501

        :return: The type of this Network.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Network.

        Type of Network {vlan, pub-vlan}  # noqa: E501

        :param type: The type of this Network.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["vlan", "pub-vlan"]  # noqa: E501
        if (self._configuration.client_side_validation and
                type not in allowed_values):
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def vlan_id(self):
        """Gets the vlan_id of this Network.  # noqa: E501

        VLAN ID  # noqa: E501

        :return: The vlan_id of this Network.  # noqa: E501
        :rtype: float
        """
        return self._vlan_id

    @vlan_id.setter
    def vlan_id(self, vlan_id):
        """Sets the vlan_id of this Network.

        VLAN ID  # noqa: E501

        :param vlan_id: The vlan_id of this Network.  # noqa: E501
        :type: float
        """
        if self._configuration.client_side_validation and vlan_id is None:
            raise ValueError("Invalid value for `vlan_id`, must not be `None`")  # noqa: E501

        self._vlan_id = vlan_id

    @property
    def dns_servers(self):
        """Gets the dns_servers of this Network.  # noqa: E501

        DNS Servers  # noqa: E501

        :return: The dns_servers of this Network.  # noqa: E501
        :rtype: list[str]
        """
        return self._dns_servers

    @dns_servers.setter
    def dns_servers(self, dns_servers):
        """Sets the dns_servers of this Network.

        DNS Servers  # noqa: E501

        :param dns_servers: The dns_servers of this Network.  # noqa: E501
        :type: list[str]
        """
        if self._configuration.client_side_validation and dns_servers is None:
            raise ValueError("Invalid value for `dns_servers`, must not be `None`")  # noqa: E501

        self._dns_servers = dns_servers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Network, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Network):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Network):
            return True

        return self.to_dict() != other.to_dict()
