# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class NetworkPortPvmInstance(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'href': 'str',
        'pvm_instance_id': 'str'
    }

    attribute_map = {
        'href': 'href',
        'pvm_instance_id': 'pvmInstanceID'
    }

    def __init__(self, href=None, pvm_instance_id=None, _configuration=None):  # noqa: E501
        """NetworkPortPvmInstance - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._href = None
        self._pvm_instance_id = None
        self.discriminator = None

        if href is not None:
            self.href = href
        if pvm_instance_id is not None:
            self.pvm_instance_id = pvm_instance_id

    @property
    def href(self):
        """Gets the href of this NetworkPortPvmInstance.  # noqa: E501

        Link to pvm-instance resource  # noqa: E501

        :return: The href of this NetworkPortPvmInstance.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this NetworkPortPvmInstance.

        Link to pvm-instance resource  # noqa: E501

        :param href: The href of this NetworkPortPvmInstance.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def pvm_instance_id(self):
        """Gets the pvm_instance_id of this NetworkPortPvmInstance.  # noqa: E501

        The attahed pvm-instance ID  # noqa: E501

        :return: The pvm_instance_id of this NetworkPortPvmInstance.  # noqa: E501
        :rtype: str
        """
        return self._pvm_instance_id

    @pvm_instance_id.setter
    def pvm_instance_id(self, pvm_instance_id):
        """Sets the pvm_instance_id of this NetworkPortPvmInstance.

        The attahed pvm-instance ID  # noqa: E501

        :param pvm_instance_id: The pvm_instance_id of this NetworkPortPvmInstance.  # noqa: E501
        :type: str
        """

        self._pvm_instance_id = pvm_instance_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NetworkPortPvmInstance, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NetworkPortPvmInstance):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NetworkPortPvmInstance):
            return True

        return self.to_dict() != other.to_dict()
