# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Version(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'build_date': 'str',
        'go_version': 'str',
        'hostname': 'str',
        'version': 'str'
    }

    attribute_map = {
        'build_date': 'buildDate',
        'go_version': 'goVersion',
        'hostname': 'hostname',
        'version': 'version'
    }

    def __init__(self, build_date=None, go_version=None, hostname=None, version=None, _configuration=None):  # noqa: E501
        """Version - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._build_date = None
        self._go_version = None
        self._hostname = None
        self._version = None
        self.discriminator = None

        if build_date is not None:
            self.build_date = build_date
        if go_version is not None:
            self.go_version = go_version
        if hostname is not None:
            self.hostname = hostname
        if version is not None:
            self.version = version

    @property
    def build_date(self):
        """Gets the build_date of this Version.  # noqa: E501

        Returns the build time  # noqa: E501

        :return: The build_date of this Version.  # noqa: E501
        :rtype: str
        """
        return self._build_date

    @build_date.setter
    def build_date(self, build_date):
        """Sets the build_date of this Version.

        Returns the build time  # noqa: E501

        :param build_date: The build_date of this Version.  # noqa: E501
        :type: str
        """

        self._build_date = build_date

    @property
    def go_version(self):
        """Gets the go_version of this Version.  # noqa: E501

        Returns the current go runtime version  # noqa: E501

        :return: The go_version of this Version.  # noqa: E501
        :rtype: str
        """
        return self._go_version

    @go_version.setter
    def go_version(self, go_version):
        """Sets the go_version of this Version.

        Returns the current go runtime version  # noqa: E501

        :param go_version: The go_version of this Version.  # noqa: E501
        :type: str
        """

        self._go_version = go_version

    @property
    def hostname(self):
        """Gets the hostname of this Version.  # noqa: E501

        Hostname of the responding system  # noqa: E501

        :return: The hostname of this Version.  # noqa: E501
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname):
        """Sets the hostname of this Version.

        Hostname of the responding system  # noqa: E501

        :param hostname: The hostname of this Version.  # noqa: E501
        :type: str
        """

        self._hostname = hostname

    @property
    def version(self):
        """Gets the version of this Version.  # noqa: E501

        Returns the git versioning information  # noqa: E501

        :return: The version of this Version.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this Version.

        Returns the git versioning information  # noqa: E501

        :param version: The version of this Version.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Version, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Version):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Version):
            return True

        return self.to_dict() != other.to_dict()
