# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class VirtualCores(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'max': 'int',
        'min': 'int',
        'assigned': 'int'
    }

    attribute_map = {
        'max': 'max',
        'min': 'min',
        'assigned': 'assigned'
    }

    def __init__(self, max=None, min=None, assigned=None, _configuration=None):  # noqa: E501
        """VirtualCores - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._max = None
        self._min = None
        self._assigned = None
        self.discriminator = None

        if max is not None:
            self.max = max
        if min is not None:
            self.min = min
        self.assigned = assigned

    @property
    def max(self):
        """Gets the max of this VirtualCores.  # noqa: E501

        The maximum DLPAR range for virtual Cores (Display only support)  # noqa: E501

        :return: The max of this VirtualCores.  # noqa: E501
        :rtype: int
        """
        return self._max

    @max.setter
    def max(self, max):
        """Sets the max of this VirtualCores.

        The maximum DLPAR range for virtual Cores (Display only support)  # noqa: E501

        :param max: The max of this VirtualCores.  # noqa: E501
        :type: int
        """

        self._max = max

    @property
    def min(self):
        """Gets the min of this VirtualCores.  # noqa: E501

        The minimum DLPAR range for virtual Cores (Display only support)  # noqa: E501

        :return: The min of this VirtualCores.  # noqa: E501
        :rtype: int
        """
        return self._min

    @min.setter
    def min(self, min):
        """Sets the min of this VirtualCores.

        The minimum DLPAR range for virtual Cores (Display only support)  # noqa: E501

        :param min: The min of this VirtualCores.  # noqa: E501
        :type: int
        """

        self._min = min

    @property
    def assigned(self):
        """Gets the assigned of this VirtualCores.  # noqa: E501

        The active virtual Cores  # noqa: E501

        :return: The assigned of this VirtualCores.  # noqa: E501
        :rtype: int
        """
        return self._assigned

    @assigned.setter
    def assigned(self, assigned):
        """Sets the assigned of this VirtualCores.

        The active virtual Cores  # noqa: E501

        :param assigned: The assigned of this VirtualCores.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and assigned is None:
            raise ValueError("Invalid value for `assigned`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                assigned is not None and assigned < 1):  # noqa: E501
            raise ValueError("Invalid value for `assigned`, must be a value greater than or equal to `1`")  # noqa: E501

        self._assigned = assigned

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VirtualCores, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VirtualCores):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VirtualCores):
            return True

        return self.to_dict() != other.to_dict()
