# coding: utf-8

"""
    IBM Power Systems for Google Cloud API

    IBM Power Systems for Google Cloud API  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: ip4g@convergetp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class VolumesClones(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'volumes_clone': 'list[VolumesClone]'
    }

    attribute_map = {
        'volumes_clone': 'volumesClone'
    }

    def __init__(self, volumes_clone=None, _configuration=None):  # noqa: E501
        """VolumesClones - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._volumes_clone = None
        self.discriminator = None

        if volumes_clone is not None:
            self.volumes_clone = volumes_clone

    @property
    def volumes_clone(self):
        """Gets the volumes_clone of this VolumesClones.  # noqa: E501

        list of volumes-clone requests  # noqa: E501

        :return: The volumes_clone of this VolumesClones.  # noqa: E501
        :rtype: list[VolumesClone]
        """
        return self._volumes_clone

    @volumes_clone.setter
    def volumes_clone(self, volumes_clone):
        """Sets the volumes_clone of this VolumesClones.

        list of volumes-clone requests  # noqa: E501

        :param volumes_clone: The volumes_clone of this VolumesClones.  # noqa: E501
        :type: list[VolumesClone]
        """

        self._volumes_clone = volumes_clone

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VolumesClones, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VolumesClones):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VolumesClones):
            return True

        return self.to_dict() != other.to_dict()
