from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from ip4g.api.authentication_api import AuthenticationApi
from ip4g.api.p_cloud_events_api import PCloudEventsApi
from ip4g.api.p_cloud_images_api import PCloudImagesApi
from ip4g.api.p_cloud_instance_ssh_keys_api import PCloudInstanceSSHKeysApi
from ip4g.api.p_cloud_instances_api import PCloudInstancesApi
from ip4g.api.p_cloud_jobs_api import PCloudJobsApi
from ip4g.api.p_cloud_networks_api import PCloudNetworksApi
from ip4g.api.p_cloud_onboarding_api import PCloudOnboardingApi
from ip4g.api.p_cloud_pvm_instances_api import PCloudPVMInstancesApi
from ip4g.api.p_cloud_placement_groups_api import PCloudPlacementGroupsApi
from ip4g.api.p_cloud_snapshots_api import PCloudSnapshotsApi
from ip4g.api.p_cloud_storage_capacity_api import PCloudStorageCapacityApi
from ip4g.api.p_cloud_storage_migration_api import PCloudStorageMigrationApi
from ip4g.api.p_cloud_system_pools_api import PCloudSystemPoolsApi
from ip4g.api.p_cloud_tasks_api import PCloudTasksApi
from ip4g.api.p_cloud_tenants_ssh_keys_api import PCloudTenantsSSHKeysApi
from ip4g.api.p_cloud_volume_replication_api import PCloudVolumeReplicationApi
from ip4g.api.p_cloud_volumes_api import PCloudVolumesApi
from ip4g.api.private_connections_api import PrivateConnectionsApi
from ip4g.api.shared_processor_pools_placement_groups_api import SharedProcessorPoolsPlacementGroupsApi
from ip4g.api.storage_types_api import StorageTypesApi
from ip4g.api.swagger_spec_api import SwaggerSpecApi
from ip4g.api.volume_transfer_api import VolumeTransferApi
